=== foss-unions/TUML/TUML.xsd
<?xml version="1.0" encoding="UTF-8"?>
   <xs:schema
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
     <xs:import namespace="http://www.w3.org/XML/1998/namespace" />
     <xs:include schemaLocation="TUML-types.xsd" />
<!-- TRADE UNIONS -->
     <xs:element name="tradeunion">
           <xs:complexType>
                 <xs:sequence>
                      <xs:element name="basicinformation">
                        <xs:complexType>
                          <xs:all>
                            <xs:element name="name" type="tu_ct_name" />
                            <xs:element name="othernames">
                                  <xs:complexType>
                                        <xs:sequence>
                                              <xs:element name="othername" type="tu_ct_name" minOccurs="1" maxOccurs="unbounded" />
                                        </xs:sequence>
                                  </xs:complexType>
                            </xs:element>
                            <xs:element name="website" type="xs:anyURI"></xs:element>
                            <xs:element name="contacts">
                              <xs:complexType>
                                <xs:sequence>
                                  <xs:element name="contact" maxOccurs="unbounded" minOccurs="0">
                                    <xs:complexType>
                                      <xs:simpleContent>
                                        <xs:extension base="gen_st_e164_phone">
                                          <xs:attribute name="type" type="gen_st_contact_type" />
                                        </xs:extension>
                                      </xs:simpleContent>
                                    </xs:complexType>
                                  </xs:element>
                                </xs:sequence>
                              </xs:complexType>
                            </xs:element>
                          </xs:all>
                        </xs:complexType>
                      </xs:element>


                       <xs:element name="meta">
                             <xs:complexType>
                                   <xs:sequence>
                                         <xs:element name="logoimages">
                                               <xs:complexType>
                                                     <xs:sequence>
                                                           <xs:element name="logoimage">
                                                                 <xs:complexType>
                                                                       <xs:attribute name="type" type="xs:string"></xs:attribute>
                                                                       <xs:attribute name="src" type="xs:anyURI"></xs:attribute>
                                                                       <xs:attribute name="size" type="xs:string"></xs:attribute>
                                                                 </xs:complexType>
                                                           </xs:element>
                                                     </xs:sequence>
                                               </xs:complexType>
                                         </xs:element>
                                        <xs:element name="history">
                                               <xs:complexType>
                                                     <xs:sequence>
                                                           <xs:element name="createdon" type="xs:date"></xs:element>
                                                           <xs:element name="updatedon" type="xs:date"></xs:element>
                                                           <xs:element name="statuses">
                                                                 <xs:complexType>
                                                                       <xs:sequence>
                                                                             <xs:element name="status" maxOccurs="unbounded">
                                                                                   <xs:complexType>
                                                                                         <xs:attribute name="from" type="xs:string"></xs:attribute>
                                                                                         <xs:attribute name="to" type="xs:string"></xs:attribute>
                                                                                         <xs:attribute name="statuscode" type="tu_st_history_status"></xs:attribute>
                                                                                   </xs:complexType>
                                                                             </xs:element>
                                                                       </xs:sequence>
                                                                 </xs:complexType>
                                                           </xs:element>
                                                     </xs:sequence>
                                               </xs:complexType>
                                         </xs:element>
                                   </xs:sequence>
                             </xs:complexType>
                       </xs:element>
                       <xs:element name="identifications">
                             <xs:complexType>
                                   <xs:sequence>
                                         <xs:element name="Identification" maxOccurs="unbounded">
                                               <xs:complexType>
                                                 <xs:simpleContent>
                                                   <xs:extension base="xs:string">
                                                     <xs:attribute name="Type" type="xs:string"></xs:attribute>
                                                     <xs:attribute name="Value" type="xs:string"></xs:attribute>
                                                   </xs:extension>
                                                </xs:simpleContent>
                                               </xs:complexType>
                                         </xs:element>
                                   </xs:sequence>
                             </xs:complexType>
                       </xs:element>
                       <xs:element name="people">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="person" type="tu_ct_person"></xs:element>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                       <xs:element name="relationships">
                             <xs:complexType>
                                   <xs:sequence>
                                         <xs:element name="relationship">
                                               <xs:complexType>
                                                     <xs:attribute name="Type" type="xs:string"></xs:attribute>
                                                     <xs:attribute name="ref" type="xs:string"></xs:attribute>
                                               </xs:complexType>
                                         </xs:element>
                                   </xs:sequence>
                             </xs:complexType>
                       </xs:element>
                 </xs:sequence>
                 <xs:attribute name="GTUUID" type="xs:string"></xs:attribute>
                 <xs:attribute name="Type" type="xs:string"></xs:attribute>
           </xs:complexType>
     </xs:element>
</xs:schema>

=== foss-unions/TUML/BALPA-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<tradeunion GTUUID="AB:CD:EF:GH:00001"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xml="http://www.w3.org/XML/1998/namespace"
  xsi:noNamespaceSchemaLocation="TUML.xsd">

<basicinformation>
    <name>British Air Line Pilots Association</name>
    <othernames>
    <othername type="Acronym" lang="en">BALPA</othername>
    </othernames>
    <website>https://www.balpa.org/</website>
    <contacts>
      <contact type="Phone">+442084764000</contact>
    </contacts>
</basicinformation>

<!-- Meta information about this union, updated dates, etc -->
<meta>
  <logoimages>
    <logoimage type="standard" src="http://test.url/logo.png" size="x-small" /> <!-- x-small, small, medium, large, x-large -->
  </logoimages>
  <history>
    <createdon>2016-06-09</createdon>
    <updatedon>2016-06-09</updatedon>
    <statuses>
      <status statuscode="Founded" from="1937-27-06" />
    </statuses>
  </history>
</meta>

<identifications>
  <Identification Type="UKLN">70</Identification>
  <Identification Type="VIAF">157655262</Identification>
  <Identification Type="ISNI">0000 0001 0527 9168</Identification>
  <Identification Type="LOC">nr2004013671</Identification>
</identifications>

<people>
  <person role="General Secretary" from="2016-01-01">
    <personaldetail>
      <GivenName>Brian</GivenName>
      <FamilyName>Strutton</FamilyName>
      <Affix type="formOfAddress">Mr</Affix>
    </personaldetail>
    <contactdetail>
      <contact type="Phone">+442084764025</contact>
      <contact type="Email">+442084764025</contact>
    </contactdetail>
  </person>
</people>

<relationships>
  <relationship Type="Parent" ref="test"></relationship>
</relationships>

</tradeunion>

=== foss-unions/TUML/TradeUnionExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<tradeunion GTUUID="AB:CD:EF:GH:00001" Type="TU"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xml="http://www.w3.org/XML/1998/namespace"
  xsi:noNamespaceSchemaLocation="TUML.xsd">

  <!-- Meta information about this union, updated dates, etc -->
  <meta>
    <logoimages>
      <logoimage type="standard" URL="http://test.url/logo.png" size="x-small" /> <!-- x-small, small, medium, large, x-large -->
    </logoimages>
    <history>
      <createdon>1/1/1900</createdon>
      <updatedon>1/1/1900</updatedon>
      <statuses>
        <status from="01/01/1900" to="" statuscode="Current" />
        <status from="01/01/1900" to="" statuscode="Merged" />
        <status from="01/01/1900" to="" statuscode="Closed" />
      </statuses>
    </history>
  </meta>

  <identifications>
    <Identification Type="WorldCat" Value="XX-XX-XXXX" />
    <Identification Type="VIAF" Value="135585641" />
  </identifications>

  <!-- The names the union identifies with, or incorporates when merging -->
  <names>
    <!--
      Type:
        OFF = Official
        AKA = Also Known As
        MRG = Incorporates another union with the name, due to merger
    -->
    <name type="OFF" lang="en">International Workers of the World</name>
    <name type="OFF" lang="jp">世界産業労働組合</name>
    <name type="AKA" lang="en">Wobblies</name>
    <name type="MRG" lang="en">Example Merged Union Name</name>
  </names>

  <relationships>
    <!--
      Type:
        Parent
        Child
        Group
    -->
    <relationship Type="Parent" ref="test"></relationship>

  </relationships>

  <industries>
    <industry SIC="00000"></industry>
    <industry SIC="00000"></industry>
  </industries>
</tradeunion>
